# Generated by Django 3.2.22 on 2023-10-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='scholarships/')),
                ('study_area', models.CharField(max_length=255)),
                ('course_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('terms_and_conditions', models.TextField()),
            ],
        ),
    ]
